### ISSUE TITLE
Filling codemeta.json 

### ISSUE THREAD

**Issue by CarloQMontangero** [Unipisa/Softi-Workbench#3]
@scatenag 

Ho provato a riempire il file, dato che Morane ne parla nel suo processo. Puoi controllare e magari suggerire quanto manca? 

Le cose che non si sanno si eliminano, no?

**Comment by scatenag** [comment]
Prova/proviamo ad usare questo per generarlo

https://codemeta.github.io/codemeta-generator/

**Comment by CarloQMontangero** [comment]
Anche questo può essere interessante: The CodeMeta Project , per trasportare da codemeta a wikidata e viceversa.

Carlo.

Da: Guido
Inviato: lunedì 1 novembre 2021 14:09
A: Unipisa/Softi-Workbench
Cc: CarloQMontangero; Assign
Oggetto: Re: [Unipisa/Softi-Workbench] Filling codemeta.json (Issue #3)

Prova/proviamo ad usare questo per generarlo
https://codemeta.github.io/codemeta-generator/
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CarloQMontangero** [comment]
Va bene il tool citato da @Guido.
